simulated_joints:
  - odom_x_joint
  - odom_y_joint
  - odom_z_joint
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  - gripper_base_gripper_left_joint
  - gripper_joint

controlled_joints:
  - odom_x_joint
  - odom_y_joint
  - odom_z_joint
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  - gripper_base_gripper_left_joint
  - gripper_joint

start_config:
  odom_x_joint: 0.0
  odom_y_joint: 0.0
  odom_z_joint: 0.0
  ur5_shoulder_pan_joint: 0.0
  ur5_shoulder_lift_joint: -0.9
  ur5_elbow_joint: 0.9
  ur5_wrist_1_joint: 0.0
  ur5_wrist_2_joint: 0.0
  ur5_wrist_3_joint: 0.0
  gripper_base_gripper_left_joint: 0.0
  gripper_joint: 0.0
projection_mode: false
sim_frequency: 100
watchdog_period: 0.1